import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Hyprland
import qs.Commons
import qs.Ui

// Forked from omarchy.workspaces 2026-08-15 to bring back old-waybar behavior:
// a workspace with windows open shows the (first) window's app icon instead
// of its number; an empty workspace still shows the plain number. Old waybar
// did this via a "workspace-taskbar" module (a community patch, not stock
// waybar) that Quattro's bar has no equivalent of.
BarWidget {
  id: root
  // moduleName is auto-derived from manifest.json's "id" (jackz.workspaces)
  // by the plugin framework. This clone's leftover explicit assignment to
  // the OLD id ("omarchy.workspaces") was fighting that -- framework sets
  // it once, this line then tried to overwrite it -- producing a repeated
  // "Cannot assign to read-only property moduleName" warning on every
  // reload (harmless, but noisy; removed 2026-08-15).

  function workspaceById(id) {
    var values = Hyprland.workspaces.values
    for (var i = 0; i < values.length; i++) {
      if (values[i].id === id) return values[i]
    }

    return null
  }

  function workspaceIds() {
    var ids = [1, 2, 3, 4, 5]
    var values = Hyprland.workspaces.values

    for (var i = 0; i < values.length; i++) {
      var id = values[i].id
      if (id > 0 && id <= 10 && ids.indexOf(id) === -1) ids.push(id)
    }

    ids.sort(function(left, right) { return left - right })
    return ids
  }

  function focusWorkspace(id) {
    if (!root.bar) return
    root.bar.run("hyprctl dispatch " + Util.shellQuote("hl.dsp.focus({ workspace = \"" + id + "\" })"))
  }

  // HyprlandToplevel exposes no direct .class/.appId — confirmed via runtime
  // introspection 2026-08-15 that both t.lastIpcObject.class (Hyprland's raw
  // client JSON) and t.wayland.appId (the linked generic Wayland toplevel)
  // carry the window class ("zen", "wechat", "md.obsidian.Obsidian", etc.),
  // agreeing with each other. Prefer lastIpcObject since it's Hyprland-native.
  // WM class often isn't the icon-theme name (e.g. Obsidian's class is the
  // reverse-DNS "md.obsidian.Obsidian" but its icon is just "obsidian").
  // Quickshell has no built-in class->icon resolver in this codebase (only
  // AppLibrary's iconIndex, which is keyed by a desktop entry's OWN icon
  // name, not by WM class), so this is a manual correction table rather
  // than a general resolver. org.omarchy.agent is Quattro's generic wrapper
  // app ID for every agent terminal (Claude Code/Cursor/opencode all launch
  // under it), so there's no per-tool icon to find here at all.
  //
  // 2026-08-15: generated by scanning EVERY installed .desktop file's
  // StartupWMClass (and filename as fallback) against its declared Icon=
  // and what icon files actually exist on disk, after individually chasing
  // Obsidian/Zen/Spotify/Claude Desktop one report at a time turned out to
  // be a much bigger, systemic pattern (Cursor hit it too). This is the
  // full scan output, filtered down to real desktop apps (dropped ~200
  // Steam games, KDE Connect variants, NoMachine helpers, etc.) rather than
  // only entries for apps seen open so far — the whole point is not
  // re-running this scan every time a new app gets reported missing.
  readonly property var iconOverrides: ({
    "md.obsidian.Obsidian": "obsidian",
    "zen": "zen-browser",
    "spotify": "spotify-launcher",
    "com.anthropic.Claude": "claude-desktop",
    "org.omarchy.agent": "utilities-terminal",
    "Cursor": "co.anysphere.cursor",
    "cursor-url-handler": "co.anysphere.cursor",
    "Bitwarden": "bitwarden",
    "Clash Verge": "clash-verge",
    "signal": "signal-desktop",
    "Pinta": "com.github.PintaProject.Pinta",
    "obs": "com.obsproject.Studio",
    "com.moonlight_stream.Moonlight": "moonlight",
    "com.orcaslicer.OrcaSlicer": "OrcaSlicer",
    "orca-slicer": "OrcaSlicer",
    "kitty-open": "kitty",
    "foot-server": "foot",
    "footclient": "foot",
    "fcitx5-configtool": "fcitx",
    "fcitx5-wayland-launcher": "fcitx",
    "org.fcitx.fcitx5-qt5-gui-wrapper": "fcitx",
    "org.fcitx.fcitx5-qt6-gui-wrapper": "fcitx",
    "calibre-ebook-viewer": "calibre-viewer",
    "calibre-lrfviewer": "calibre-viewer",
    "blueman-adapters": "blueman-device",
    "blueman-manager": "blueman",
    "retroarch": "com.libretro.RetroArch",
    "xreal-cinema": "video-display",
    "xreal-kodi": "video-display",
    "xreal-offline-library": "video-x-generic",
    "xreal-exit": "system-shutdown",
    "xreal-steam": "steam",
    "vr-video": "video-x-generic",
    "flying-carpet": "network-wireless",
    "system-config-printer": "printer",
  })

  // 2026-08-15: Cursor's real class is lowercase "cursor" but its .desktop
  // file (and my exact-match override table, first pass) used "Cursor" —
  // silently missed. Matching case-insensitively so this class of typo/
  // casing mismatch stops being a one-report-at-a-time whack-a-mole too.
  readonly property var iconOverridesLower: {
    var out = {}
    for (var k in root.iconOverrides) out[k.toLowerCase()] = root.iconOverrides[k]
    return out
  }

  function firstAppId(workspace) {
    if (!workspace || !workspace.toplevels || workspace.toplevels.values.length === 0) return ""
    var t = workspace.toplevels.values[0]
    var guess = (t.lastIpcObject && t.lastIpcObject.class) || (t.wayland && t.wayland.appId) || ""
    guess = String(guess || "")
    return root.iconOverridesLower[guess.toLowerCase()] || guess
  }

  readonly property real trailingGap: root.vertical ? 0 : Style.spaceReal(1.5)

  implicitWidth: grid.implicitWidth + trailingGap
  implicitHeight: grid.implicitHeight

  GridLayout {
    id: grid
    anchors.fill: parent
    anchors.rightMargin: root.trailingGap
    columns: root.vertical ? 1 : root.workspaceIds().length
    columnSpacing: root.vertical ? 0 : Style.space(1)
    rowSpacing: root.vertical ? Style.space(2) : 0

    Repeater {
      model: root.workspaceIds()

      Item {
        id: cell
        required property int modelData

        readonly property var workspace: root.workspaceById(modelData)
        readonly property bool occupied: workspace !== null && workspace.toplevels.values.length > 0
        readonly property bool focused: Hyprland.focusedWorkspace !== null && Hyprland.focusedWorkspace.id === modelData
        readonly property string appId: cell.occupied ? root.firstAppId(cell.workspace) : ""
        // iconFailed flips true once Quickshell.iconPath resolves to nothing
        // usable for this appId (e.g. Cursor: its own .desktop entry points
        // at "co.anysphere.cursor", which isn't installed anywhere on this
        // system — confirmed 2026-08-15, not just a lookup-name mismatch).
        // Reset per appId so a workspace switching apps re-attempts the
        // lookup instead of staying permanently stuck in fallback.
        property bool iconFailed: false
        onAppIdChanged: iconFailed = false
        readonly property bool showIcon: cell.occupied && !cell.focused && cell.appId !== "" && !cell.iconFailed

        implicitWidth: btn.implicitWidth
        implicitHeight: btn.implicitHeight

        WidgetButton {
          id: btn
          bar: root.bar
          text: focused ? "󱓻" : (modelData === 10 ? "0" : String(modelData))
          labelVisible: !cell.showIcon
          opacity: cell.occupied || cell.focused ? 1 : 0.5
          horizontalMargin: 6
          verticalPadding: 6
          fixedWidth: root.vertical ? root.barSize : Style.space(20)
          fixedHeight: root.barSize
          tooltipText: cell.appId
          onPressed: function() { root.focusWorkspace(cell.modelData) }
        }

        Image {
          visible: cell.showIcon
          anchors.centerIn: btn
          // Fixed pixel size, NOT Style.space() -- Style.space() is
          // multiplied by [spacing].scale (and font base-size, since
          // scale-with-font is on), so it would shrink/grow with
          // omarchy-bar-scale along with everything else. jackz wants app
          // icons to stay put while the rest of the bar scales (2026-08-15).
          width: 22
          height: 22
          fillMode: Image.PreserveAspectFit
          asynchronous: true
          sourceSize.width: width * Screen.devicePixelRatio
          sourceSize.height: height * Screen.devicePixelRatio
          source: cell.showIcon ? Quickshell.iconPath(cell.appId, true) : ""
          // Blank/unresolved icon lookups fall back to the plain number
          // (via cell.iconFailed -> showIcon -> btn.labelVisible) rather
          // than leaving an empty slot with neither icon nor number.
          onStatusChanged: if (status === Image.Error) cell.iconFailed = true
        }
      }
    }
  }
}
