# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    rounding = 14
    rounding_power = 2.8
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#group
group {
    groupbar {
        rounding = 12
        rounding_power = 2.8
        gradient_rounding = 12
        gradient_rounding_power = 2.8
    }
}

# Keep popped tiles consistent with global rounding
windowrule = rounding 14, match:tag pop
