-- Ported from ~/.config/hypr/{monitors,workspaces-dock}.conf  (2026-08-11, DRAFT)
--
-- monitors.conf was generated by hyprmoncfg as `monitorv2 { ... }` blocks.
-- hl.monitor() is the Lua form of monitorv2.
--
-- VERIFY AFTER UPGRADE: sdr_min_luminance / sdr_max_luminance are monitorv2-only
-- keys. If hl.monitor() rejects them, drop them (they only matter for HDR
-- tonemapping on the Studio Display) or set them with
-- `hyprctl keyword monitorv2[...]`. Check with: hyprctl monitors all

local studio = "desc:Apple Computer Inc StudioDisplay 0x4E83B9D6"
local laptop = "desc:Samsung Display Corp. ATNA40HQ10-0  0x0000003F"
--                                                     ^^ two spaces, as in the
--                                                     original desc. Do not
--                                                     "tidy" this or the match
--                                                     silently stops working.

hl.monitor({
  output = studio,
  mode = "5120x2880@60.00",
  position = "0x0",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = laptop,
  mode = "2880x1800@60.00",
  position = "2560x0",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

-- ── Workspace ↔ monitor map (was workspaces-dock.conf) ────────────────────────
-- 5–7 stay on the ThinkPad panel; everything else prefers the Studio Display.
-- If a bound monitor is absent, Hyprland falls back to the first available.
-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

for _, ws in ipairs({ 1, 2, 3, 4, 8, 9, 10 }) do
  hl.workspace_rule({ workspace = tostring(ws), monitor = studio })
end

for _, ws in ipairs({ 5, 6, 7 }) do
  hl.workspace_rule({ workspace = tostring(ws), monitor = laptop })
end
